export const NewRegData = [
  {
    id: 1,
    key: 1,
    firstName: 'Haylie',
    lastName: 'George',
    country: 'Los Angeles',
    email: 'j.bates@gmail.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 2,
    key: 2,
    firstName: 'Ashlynn',
    lastName: 'Botos',
    country: 'Austin',
    email: 'terry.steven@hotmail.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 3,
    key: 3,
    firstName: 'Maren',
    lastName: 'Konsgaard',
    country: 'San Diego',
    email: 'a.ray@msn.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 4,
    key: 4,
    firstName: 'Marley',
    lastName: 'George',
    country: 'New Orleans',
    email: 's.reed@gmail.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 5,
    key: 5,
    firstName: 'Haylie',
    lastName: 'Dokidis',
    country: 'Virginia Beach',
    email: 'c.perry@hotmail.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 6,
    key: 6,
    firstName: 'Madelyn',
    lastName: 'Geidt',
    country: 'Arlington',
    email: 'andre.jennings@aol.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 7,
    key: 7,
    firstName: 'Tatiana',
    lastName: 'Siphron',
    country: 'Portland',
    email: 'jessie.evans@gmail.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 8,
    key: 8,
    firstName: 'Aspen',
    lastName: 'Vetrovs',
    country: 'Jacksonville',
    email: 'melvin.shelton@aol.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 9,
    key: 9,
    firstName: 'Tatiana',
    lastName: 'Calzoni',
    country: 'Fresno',
    email: 'audrey.anderson@outlook.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 10,
    key: 10,
    firstName: 'Jordyn',
    lastName: 'Kenter',
    country: 'Nashville',
    email: 'j.austin@msn.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 11,
    key: 11,
    firstName: 'Haylie',
    lastName: 'George',
    country: 'Los Angeles',
    email: 'j.bates@gmail.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 12,
    key: 12,
    firstName: 'Ashlynn',
    lastName: 'Botos',
    country: 'Austin',
    email: 'terry.steven@hotmail.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 13,
    key: 13,
    firstName: 'Maren',
    lastName: 'Konsgaard',
    country: 'San Diego',
    email: 'a.ray@msn.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 14,
    key: 14,
    firstName: 'Marley',
    lastName: 'George',
    country: 'New Orleans',
    email: 's.reed@gmail.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 15,
    key: 15,
    firstName: 'Haylie',
    lastName: 'Dokidis',
    country: 'Virginia Beach',
    email: 'c.perry@hotmail.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 16,
    key: 16,
    firstName: 'Madelyn',
    lastName: 'Geidt',
    country: 'Arlington',
    email: 'andre.jennings@aol.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 17,
    key: 17,
    firstName: 'Tatiana',
    lastName: 'Siphron',
    country: 'Portland',
    email: 'jessie.evans@gmail.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 18,
    key: 18,
    firstName: 'Aspen',
    lastName: 'Vetrovs',
    country: 'Jacksonville',
    email: 'melvin.shelton@aol.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 19,
    key: 19,
    firstName: 'Tatiana',
    lastName: 'Calzoni',
    country: 'Fresno',
    email: 'audrey.anderson@outlook.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  },
  {
    id: 20,
    key: 20,
    firstName: 'Jordyn',
    lastName: 'Kenter',
    country: 'Nashville',
    email: 'j.austin@msn.com',
    organization: 'Commscope',
    jobTitle: 'Marketing',
    jobFunction: 'Marketing',
    event: 'Taiwan Event',
    mobileNumber: '852 1234 5678',
    expandable: true
  }
]